version: 2
jobs:
  build:
    working_directory: ~/todolist/server
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          PGHOST: 127.0.0.1
          PGUSER: circleci
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
    steps:
      - checkout

      - run: sudo apt update && sudo apt install -y postgresql-client || true

      - run: sudo gem update --system

      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run: bundle exec bin/rails test